### PR TITLE
Footer styling and content

### LINKED ISSUE #141: Style footer so it looks different than rest of page

### LINKED ISSUE #218: Add privacy policy to footer
It's a shortcode called `privacy_policy.html`; I don't recall why I made it a shortcode and not a partial before, but there must have been a reason.

### LINKED ISSUE #263: determine contents of footer
Discussing the privacy policy in https://github.com/devopsdays/devopsdays-theme/issues/218 and the footer styling in https://github.com/devopsdays/devopsdays-theme/issues/141 I think there needs to be a different, more-general discussion of what exactly is in the footer.

Here's what's on the current prod site:
screen shot 2017-02-20 at 12 32 27 pm

The current links are: 
1) twitter.com/devopsdays (doesn't need its own link; it's low-traffic and we have a feed it's part of)
2) An email icon to the old contact page (obviated by the updated About)
3) The blog feed (now linked from the blog section in the new footer)
4) The code of conduct (now linked from the About section in the new footer)
5) The privacy policy (now linked from the About section in the new footer)

The current dev site has this:
screen shot 2017-02-20 at 12 32 12 pm

1) Redundant and not-logical events links
2) Featured (something we haven't figured out how to use effectively)
3) Blog (mostly okay but would look better with two entries and an RSS link)
4) Twitter feed (mostly okay but visually heavy to the right)

My proposed PR https://github.com/devopsdays/devopsdays-theme/pull/262 has this:

screen shot 2017-02-20 at 12 31 52 pm

1) Twitter feed is tall so looks nicer on the left
2) Blog, adjusted to have 2 entries and an RSS link
3) List to open CFPs (I'm fine with this being something else or not existing if we want three wider ones - this struck me as something that a) changes and b) is an interesting call to action.)
4) About - lower right is a traditional spot for the "about us" stuff.

### PR DESCRIPTION
**Pull request by mattstratton**
Fixes #263 
Fixes #218 
Fixes #141 

Signed-off-by: Matt Stratton <matt.stratton@gmail.com>

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
It's a good start; I'd prefer the four columns I showed in https://github.com/devopsdays/devopsdays-theme/issues/263 (in that order) but I'm willing to discuss this option. (Is this intended as just the beginning? In which case cool, let's get it in and then iterate.)

**Comment by mattstratton** [comment]
Maybe the PR is jacked, but I did exactly those columns.

**Comment by bridgetkromhout** [comment]
Based on Slack it sounds like there is still a branch to be pushed up. Thanks!

**Comment by mattstratton** [comment]
@bridgetkromhout this PR has been updated :)

Still a little more hacking I want to do, but just want to make sure this looks good to you.

**Pull request merged**
