### PR TITLE
Change verbiage on speaker page to not be talk-specific

### LINKED ISSUE #554: Refactor how "talks" are displayed on a speaker's page
In order to support the idea of workshops, etc, we need to change how the items associated with a speaker are displayed. Currently, it looks like this:

The use of the word "talks" is a little odd, because it also includes ignites and workshops. Rather than breaking it down into "workshops by...", "talks by...", etc, it should just list all the presentations (for lack of a better word) that this person is presenting/responsible for.

We can solve this two ways:

1) Keep the same layout idea (with a title) and change "talks" to "presentations", which might be misleading.
2) Remove the idea of a title element altogether, and figure out a way to display the list in a method that doesn't require descriptive text.

### PR DESCRIPTION
**Pull request by mattstratton**
Fixes #554

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
No netlify preview but it _looks_ about right.

**Comment by mattstratton** [comment]
It's processing still.

**Comment by mattstratton** [comment]
Example: https://deploy-preview-559--devopsdays-theme.netlify.com/events/2017-ponyville/speakers/fluttershy/

**Comment by bridgetkromhout** [comment]
Looks perfect.

**Pull request merged**
