### PR TITLE
[Fixes #490] Add support for multiple session days

### LINKED ISSUE #490: Support more than two-day events in automated program - IDEA 81
<p>Yvo just sent you some feedback - and they're feeling 😀 about it! </p><p>If the program builder supported 3 (or really X) day devopsdays events. Currently when I want to define the program via the event data yml, it keys off of the first and last date, but is not happy if there is an undocumented third date. </p>

[ProdPad URL](https://portal.prodpad.com/24442/ideas/373872)

Effort: 4/10
Impact: 5/10

### PR DESCRIPTION
**Pull request by kikicarbonell**
Issue: #490 

This code need the new variable in data yaml: `eventdates` with an array of String of dates. Ex:
```
...
eventdates: ["2016-10-18","2016-10-19","2016-10-20","2016-10-21"]
...
```

### CODE REVIEW

**Comment by mattstratton** [comment]
This is a good start. I'll dig into it a big more. We definitely need to add some backwards compatibility (any time we introduce a new data element, we have to make sure that we don't need to update events that didn't have it).

For example, you can see now that with this change, the program for Ponyville is broken:

https://deploy-preview-492--devopsdays-theme.netlify.com/events/2017-ponyville/program

**Comment by kikicarbonell** [comment]
I have some ideas now to build dates structures based on program dates declaration:

1st.: iterate .program to build eventdates variable them reuse my code to paint div (limitation: needed two iteration)

2nd.: iterate .program and if the session date is new add to eventdates and paint div header and session, if the session exist paint session (limitation: assumption session in order on .program)

I prefer 2nd. because use only one iteration to paint program. What do you think?

**Comment by mattstratton** [comment]
I hacked this together in #493 - the accordion isn't working yet but it's a bit more elegant and doesn't require new data elements.

**Comment by kikicarbonell** [comment]
My last change don't need extra data but I don't know the reason of day_displayed lost values...is problem of Go or Hugo template with variable scope?

**Comment by kikicarbonell** [comment]
This also doesn't handle ignites yet too.

**Comment by mattstratton** [comment]
yeah, scope is a problem in go templates. That's why Scratch is super helpful. 

https://hugodocs.info/functions/scratch/#scratch

I'm about 99% there with my branch; I need to fix the Ignites (using the same logic; I just forgot about them) and figure out why I broke the javascript :)

**Comment by mattstratton** [comment]
Duplicate effort from #493, but thank you for bringing this to the forefront and for contributing!!

**Comment by bridgetkromhout** [comment]
Thank you, @kikicarbonell! Even though this wasn't merged we appreciate your work here, and it informed the result!

**Pull request closed without merging**
