### PR TITLE
[refs #00611] Add ability to use custom_url in program page

### LINKED ISSUE #611: Allow URL link on "custom" program type
When creating a program item of type "custom", there should be a sub-element of "custom_url" which can link somewhere else.

Actually, this should work on all types, in case somebody wants to link elsewhere for reasons.

### PR DESCRIPTION
**Pull request by chriscoffee**
Hey :wave: 

This PR should add the ability to add a custom_url for all types on the
program page and fix #611. (I meant to get this in sooner but there's a terrible flu going around the UK at the moment!)

By adding `custom_url: "https://example.com/valid-url"`in talk/ignite/custom/workshop you'll replace the link with one that's external and opens in a new window.

For what is essentially a simple change I also took it upon myself to alter the indenting and remove a number of unused tags. This can be reverted easily if I overstepped here slightly. The following tags weren't used:

https://github.com/devopsdays/devopsdays-theme/blob/28e6c40a59993c27b0d4f694583fe814fc6c2f6d/layouts/program/single.html#L61

https://github.com/devopsdays/devopsdays-theme/blob/28e6c40a59993c27b0d4f694583fe814fc6c2f6d/layouts/program/single.html#L150-L151

As a future point I feel like in the future we could probably refactor this template which will probably improve the build performance slightly but that's a future consideration. (Average CPU time duration for that template is ~53s)

---
This change is [Reviewable](https://reviewable.io/reviews/devopsdays/devopsdays-theme/645)

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hey, thanks for getting started on this! Please don't open a new window for people - people can choose to open a new window if they want, but as a stylistic choice we don't have anything on the site making that call for the end users.

**Comment by mattstratton** [comment]
@chriscoffee Because of some other changes merged, I think you want to rebase and submit the PR again (also please see @bridgetkromhout request as well). Thanks!

**Comment by mattstratton** [comment]
I did my best to merge the existing changes with your updates here, @chriscoffee - let's see if it works!

**Comment by mattstratton** [comment]
Seems to be working - can't get a build out of netlify right now (it's hung) but if we merge this, we can see it on dev.devopsdays.org and check it out there. 

I removed the "open in new window/tab" per @bridgetkromhout request.

**Pull request merged**
