### PR TITLE
Remove filesystem deps

### LINKED ISSUE #471: Remove filesystem deps
With the use of the `relURL` function, we can determine the URL path of an element and we should be able to use that to decide which event, year, etc it is instead of this same copy-pasted code we keep using: 

```
{{ $path := split $.Source.File.Path .Site.Params.PathSeparator }}
{{ $event_slug := index $path 1 }}
{{ $e :=  (index $.Site.Data.events $event_slug) }}
{{/* end site data query */}}
```

I already do this a little bit; for example, in `partials/head/seo/schema.html` there is this code:

```
  {{ $path := split ( .Permalink | relURL) "/" }}
  {{ $event_slug := index $path 2 }}
```

This might sound pedantic, but it has a far-reaching effect; it removes the need for a Windows-specific config file, because we are not splitting on filesystem paths anymore. 

TBH, I'm not 100% sold that the `PathSeparator` value is really truly needed anyway; we have places in the code where it doesn't need it. Although that night be that Go is using some OS callbacks for us in the function. For example:

```
{{ $.Scratch.Set "contentdir" (printf "static/events/%s/" $event_slug) }}
  {{if (where (readDir "static/events") "Name" $event_slug)}}
```

You would think that would NOT work on Windows, because the paths it is checking for with `readDir` are not Windows-friendly, but I am guessing `readDir` knows how to handle this.

### PR DESCRIPTION
**Pull request by mattstratton**
Fixes #471 

This definitely depends upon baseURL being set properly, so we will need to make sure that we update the netlify scripts in production before releasing this.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
> so we will need to make sure that we update the netlify scripts in production before releasing this.

It would be good to document (here or in the associated issue of https://github.com/devopsdays/devopsdays-theme/issues/471) exactly how to update the netlify scripts in production.

**Comment by mattstratton** [comment]
> It would be good to document (here or in the associated issue of #471) exactly how to update the netlify scripts in production.

Just need to copy the two shell scripts from `bin` in this project into `bin` in `devopsdays-web`. They're the same :)

**Comment by mattstratton** [comment]
Also, in the `devopsdays-web` version of `appveyor.yml` we need to modify this line:
`hugo --verbose --config config-windows.toml`
to
`hugo --verbose`

**Comment by mattstratton** [comment]
And...we should remove the pathseparator keys from the config.toml, and update the windows config toml file, although it's not needed anymore (but some people might be using it).

Or we could just delete it and have them find out the hard way :)

**Comment by mattstratton** [comment]
This document refers to the windows TOML file that isn't needed anymore after this version is released:

https://github.com/devopsdays/devopsdays-web/blob/master/CONTRIBUTING.md

**Comment by bridgetkromhout** [comment]
LGTM! :shipit:

**Pull request merged**
