### PR TITLE
Make program look much prettier

### LINKED ISSUE #435: Contextually style program elements - IDEA 17
<p style=' color: rgb(36, 41, 46); font-family: -apple-system, system-ui, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; font-size: 14px; text-align: start; background-color: rgb(255, 255, 255);'>We should maybe add some special styling for Ignites or open space elements in the data file - ignites could be clickable to an anchor tag lower on the page to the ignite section too.</p><p style=' color: rgb(36, 41, 46); font-family: -apple-system, system-ui, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; font-size: 14px; text-align: start; background-color: rgb(255, 255, 255);'>Since the item blocks aren&#39;t really styled at all right now, we don&#39;t have a good way of doing this. I am thinking this could be an extension where we have some default &quot;types&quot; (right now I think it&#39;s just <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>talk</code> or <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>custom</code>, but we could add <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>open-space</code>, <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>ignites</code>, and maybe <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>sponsors</code> which would result in some different behavior/formatting).</p><p style=' color: rgb(36, 41, 46); font-family: -apple-system, system-ui, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; font-size: 14px; text-align: start; background-color: rgb(255, 255, 255);'>My theory is that for example, if the element is of type <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>ignites</code>, it would be a link to the anchor of the ignites section (which won&#39;t do much on a big screen, but will be awesome on a small one). And for <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>open-spaces</code>, it could have a different color or something.</p>

[ProdPad URL](https://portal.prodpad.com/24442/ideas/357419)

### LINKED ISSUE #496: Program layout should not be evenly spread
Times do not need to take up as much space as the content.

### LINKED ISSUE #497: Remove accordion from program listing
Pretty sure nobody will miss it.

### PR DESCRIPTION
**Pull request by mattstratton**
This commit makes Ignites occur inline (removing the reference at the bottom).

It also adds color-coding depending upon the type.

Fixes #497 
Fixes #496 
Fixes #435

### CODE REVIEW

**Comment by mattstratton** [comment]
See it in action!

https://deploy-preview-498--devopsdays-theme.netlify.com/events/2017-ponyville/program

**Comment by mattstratton** [comment]
Mobile view:

img_4112

compared to existing mobile view:
img_4113

**Comment by bridgetkromhout** [comment]
I really like the look of this; nice work. I suspect people will be happier if they can override the colors. Is that possible with what you've added thus far?

**Comment by mattstratton** [comment]
It's sorta possible. I thought about adding it in this way...have an additional, optional attribute for each element where you can specify the hex value of the background color.

HOWEVER...CSS gets bad in some cases. Because you also have to say what color is the text? What color are the links? etc.

**Comment by bridgetkromhout** [comment]
> I thought about adding it in this way...have an additional, optional attribute for each element where you can specify the hex value of the background color.

Right, basically I was thinking, we start with a recommended happy-path that looks decent. If people override and it looks terri-bad, that's possible but we'll at least recommend that they don't.

**Comment by mattstratton** [comment]
One of the things I'm toying with once we go to hugo 0.20 is that events can actually specify some stuff specifically, like colors, in their config file. Since we can create different file types in hugo 0.20, it could be something like if you set the color scheme options in your data file, it will create something like `events/2017-ponyville/2017-ponyville.css` which it will then embed in the `<head>` of your pages only.

**Comment by bridgetkromhout** [comment]
This looks good. I suspect people will try to do their own layout inside the ignites block - anything we can anticipate and guide might be a good idea - but overall, this is excellent.

**Comment by mattstratton** [comment]
> I suspect people will be happier if they can override the colors. 

I added #511 to add this feature. I think we can deploy this without the feature and add it later, although I might try to get it in now.

**Comment by mattstratton** [comment]
Commit 9133ded5197919ab0fe50efcc3c665af6344fdfc adds the ability for color overrides.

**Pull request merged**
