### PR TITLE
Move map to below grid

### LINKED ISSUE #516: Move map to below city icons
Given that the grid of cities is much more visually appealing than the map, it's been proposed to bring the map BELOW the city grid.

This will also help performance, as it removes "above the fold" blocking javascript.

### PR DESCRIPTION
**Pull request by mattstratton**
This is a WIP just to see what it looks like to have the map below the grid

Fixes #516

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
What I really like about this is that "above the fold" you get more interesting and timely visuals that change more frequently. And we still have the full map too.

**Comment by mattstratton** [comment]
There is a performance improvement with this as well - with the map at the top, there is blocking JavaScript from rendering the view. That is to say, even though it's async, the "above the fold" content (which in the current state) is the map, which takes a few seconds to load, so the load perception is slow.

**Comment by MikeRosTX** [comment]
IMO it looks great below the folders.

But I was wondering if it would **REALLY** improve performance if we had the maps in a link underneath **PAST EVENTS** called **WORLD MAP**.

Realistically, the map is visual.  Do we have stats of how much that map gets used?

**Comment by mattstratton** [comment]
It's about perceived load time, actually. The load time for the page to be usable isn't affected by the async javascript; it just means that the "above the fold" content (which is the map) doesn't show up as quickly.

The map is a huge part of the "brand" of the devopsdays site; I think it still belongs on the home page. The map is not likely to be used as a navigation element, but more to reflect the "global" nature of devopsdays, so it's a big part of the brand.

**Comment by bridgetkromhout** [comment]
I haven't seen any objections. I think this is good to go.

**Pull request merged**
